[pytest]
minversion = 7.0
addopts = -v -s --tb=short --strict-markers

markers =
    smoke: Маркер для smoke-тестов
    regression: Mark for regression tests
    slow: Тесты, которые выполняются долго

testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
